<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="BepInEx.Core">
      <HintPath>F:\Game\TwinkleStarKnights\Twinkle_StarKnightsX\BepInEx\core\BepInEx.Core.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx.Unity.IL2CPP">
      <HintPath>F:\Game\TwinkleStarKnights\Twinkle_StarKnightsX\BepInEx\core\BepInEx.Unity.IL2CPP.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppInterop.Runtime">
      <HintPath>F:\Game\TwinkleStarKnights\Twinkle_StarKnightsX\BepInEx\core\Il2CppInterop.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Il2Cppmscorlib">
      <HintPath>F:\Game\TwinkleStarKnights\Twinkle_StarKnightsX\BepInEx\interop\Il2Cppmscorlib.dll</HintPath>
    </Reference>
    <Reference Include="spine-unity">
      <HintPath>F:\Game\TwinkleStarKnights\Twinkle_StarKnightsX\BepInEx\interop\spine-unity.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>F:\Game\TwinkleStarKnights\Twinkle_StarKnightsX\BepInEx\interop\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ImageConversionModule">
      <HintPath>F:\Game\TwinkleStarKnights\Twinkle_StarKnightsX\BepInEx\interop\UnityEngine.ImageConversionModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>F:\Game\TwinkleStarKnights\Twinkle_StarKnightsX\BepInEx\unity-libs\UnityEngine.InputLegacyModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>F:\Game\TwinkleStarKnights\Twinkle_StarKnightsX\BepInEx\interop\UnityEngine.UI.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
